% MATLAB Code from Radar Waveform Analyzer App
% Generated by MATLAB 9.14 and Phased Array System Toolbox 5.0
% Generated on 27-Aug-2023 19:18:08

% Create a Linear FM Waveform object
Waveform = phased.LinearFMWaveform('SampleRate',1.5e+06,...
        'PulseWidth',6.66667e-05,'PRF',1500,'SweepBandwidth',1e+06,...
        'SweepDirection','Up','SweepInterval','Positive'...
        ,'Envelope','Rectangular','NumPulses',1,'FrequencyOffset',0);
Fs = Waveform.SampleRate;
% Call step method of Waveform to generate IQ samples of Waveform
x = Waveform();

% Create figure for Real and Imaginary
figure;
   l = (0:length(x)-1)/Fs;
subplot(2,1,1);
   [~, scale, ~] = engunits(l(end));
   l = l*scale;
   plot(l,real(x));
   axis([0 700 -1.0913 1.1]);
   xlabel('');
   ylabel('Amplitude: Real Part (V)');
   grid on;
subplot(2,1,2);
    plot(l,imag(x));
    axis([0 700 -1.1 1.0998]);
    xlabel('Time (\mus)');
    ylabel('Amplitude: Imaginary Part (V)');
    grid on;

% Create figure for Magnitude and Phase
figure;
    l = (0:length(x)-1)/Fs;
    [~, scale, ~] = engunits(l(end));
    l = l*scale;
subplot(2,1,1);
    plot(l,abs(x));
    axis([0 700 -0.1 1.1]);
    xlabel('');
    ylabel('Magnitude (V)');
    grid('on');
subplot(2,1,2);
    plot(l,angle(x));
    axis([0 700 -3.3175 3.3175]);
    xlabel('Time (\mus)');
    ylabel('Phase (rad)');
    grid('on');

% Create figure for Spectrum
figure;
    pwelch(x, [], [], [], Fs, 'centered');
    xlabel('Frequency (kHz)');
    ylabel('Power/Frequency (dB/Hz)');
    title('Power Spectral Density of Baseband Signal');

% Create a Matched Filter object
coeff = getMatchedFilter(Waveform);
Compression = phased.MatchedFilter('Coefficients',coeff(:,1), ...
'SpectrumWindow','None');
y = Compression(x);
