
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 23.2 and Phased Array System Toolbox 23.2

% Generated on 03-Nov-2023 12:01:20

% Create a uniform rectangular array
Array = phased.URA('Size',[10 10],...
    'Lattice','Rectangular','ArrayNormal','x');
% The multiplication factor for lambda units to meter conversion
Array.ElementSpacing = [0.5 0.5]*0.15;
% Calculate Row taper
rwind = ones(1,10).';
% Calculate Column taper
cwind = ones(1,10).';
% Calculate taper
taper = rwind*cwind.';
Array.Taper = taper.';

% Create an isotropic antenna element
Elem = phased.IsotropicAntennaElement;
Elem.BackBaffled = true;
Elem.FrequencyRange = [0 2000000000];
Array.Element = Elem;

% Assign Frequencies and Propagation Speed
Frequency = 2000000000;
PropagationSpeed = 300000000;


% Create Figure

% Plot Array Geometry
figure;
viewArray(Array,'ShowNormals',false,...
    'ShowTaper',false,'ShowIndex','None',...
    'ShowLocalCoordinates',true,'ShowAnnotation',false,...
    'Orientation',[0;0;0]);

% Calculate Steering Weights

Freq3D = 2000000000;
% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 3d graph
format = 'polar';
plotType = 'Directivity';
figure;
pattern(Array, Freq3D , 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format,'weights', w(:,1),...
    'ShowArray',false,'ShowLocalCoordinates',true,...
    'ShowColorbar',true,'Orientation',[0;0;0],...
    'Type', plotType);

